services:
  portfolio-front:
    container_name: portfolio-front
    build:
      context: ./front   # <- ajuste para o diretório onde está seu front
      dockerfile: Dockerfile
    ports:
      - "3080:80"
    restart: unless-stopped # Política de reinício para produção