services:
  portfolio-front:
    image: ghcr.io/${REPO_OWNER}/portfolio_v2/portfolio-front:latest
    container_name: portfolio-front
    restart: unless-stopped
    env_file:
      - .front.env
    networks:
      - portfolio-network
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.power-viewer.rule=Host(`portfolio.joaovictorr.dev`)"
      - "traefik.http.routers.power-viewer.entrypoints=websecure"
      - "traefik.http.routers.power-viewer.tls.certresolver=myresolver"
      - "traefik.http.services.power-viewer.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy-network"

networks:
  portfolio-network:
    name: portfolio-network
    driver: bridge
  proxy-network:
    external: true
