services:
  portfolio-front:
    image: ghcr.io/${REPO_OWNER}/portfolio_v2/portfolio-front:latest
    container_name: portfolio-front
    restart: unless-stopped
    env_file:
      - .front.env
    networks:
      - portfolio-network
      - proxy-network

networks:
  portfolio-network:
    name: portfolio-network
    driver: bridge
  proxy-network:
    external: true
