server {
    listen 80;

    server_name _;

    location / {
        return 301 https://joaovictorr.dev$request_uri;
    }
}

server {
    listen 443;

    server_name _;

    location / {
        return 301 https://joaovictorr.dev$request_uri;
    }
}